name: "frontend check"

runs:
  using: "composite"
  steps:
    - name: lint
      run: npm run lint
      working-directory: backend
      shell: bash

    - name: test
      run: npm run test:all
      working-directory: backend
      shell: bash
