name: "backend check"

runs:
  using: "composite"
  steps:
    - name: satisfy macro
      run: mkdir frontend/target
      shell: bash

    - name: fmt
      run: cargo fmt --check -q
      working-directory: backend
      shell: bash

    - name: lint
      run: cargo check -q
      working-directory: backend
      shell: bash

    - name: clippy
      run: cargo clippy -q
      working-directory: backend
      shell: bash

    - name: test
      run: cargo test
      working-directory: backend
      shell: bash
