name: "backend check"

runs:
    using: "composite"
    steps:
        - name: lint
          run: cargo check -q
          working-directory: src-tauri
          shell: bash

        - name: clippy
          run: cargo clippy -q
          working-directory: src-tauri
          shell: bash

        - name: fmt
          run: cargo fmt --check -q
          working-directory: src-tauri
          shell: bash

        - name: test
          run: cargo test
          working-directory: src-tauri
          shell: bash
