name: "frontend install"

runs:
  using: "composite"
  steps:
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 24

    - name: install frontend dependencies
      run: npm ci
      working-directory: frontend
      shell: bash
