name: "backend install"

inputs:
  platform:
    required: false
    default: "unknown"

runs:
  using: "composite"
  steps:
    - name: install dependencies (ubuntu only)
      if: startsWith(inputs.platform, 'ubuntu')
      run: >
        sudo apt-get update

        sudo apt-get install -y \
          libgtk-3-dev \
          libwebkit2gtk-4.0-dev \
          libappindicator3-dev \
          librsvg2-dev \
          patchelf
      shell: bash

    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable
