name: "check frontend"
on:
    push:
        branches: [next]
    pull_request:
        branches: [main, next]

jobs:
    check-frontend:
        runs-on: "ubuntu-latest"

        steps:
            - uses: actions/checkout@v3

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: install frontend dependencies
              run: npm install

            - name: lint
              run: npm run lint

            - name: test
              run: npm run test:all
