name: "check frontend"

on:
    pull_request:
        branches: [main]

jobs:
    check-frontend:
        runs-on: "ubuntu-latest"

        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/frontend-install
            - uses: ./.github/actions/frontend-check
