name: "publish"

on:
    push:
        branches: [main]

jobs:
    publish-tauri:
        permissions:
            contents: write

        strategy:
            fail-fast: false
            matrix:
                platform: [windows-latest]

        runs-on: ${{ matrix.platform }}

        steps:
            - uses: actions/checkout@v3

            # Prepare and check frontend
            - uses: ./.github/actions/frontend-install
            - uses: ./.github/actions/frontend-check

            # Prepare and check backend
            - uses: ./.github/actions/backend-install
              with:
                  platform: ${{matrix.platform}}

            # Build executeables
            - uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
              with:
                  tagName: ticit-v__VERSION__
                  releaseName: "Ticit v__VERSION__"
                  releaseBody: "See the assets to download this version and install."
